[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  NITRO_PRESET = "netlify"
  SECRETS_SCAN_ENABLED = "false"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false